FROM nginx:alpine

RUN rm -rf /usr/share/nginx/html/*

COPY ./sms-web/dist /usr/share/nginx/html/

RUN echo '<!DOCTYPE html><html><head><title>SMS Platform</title></head><body><h1>Loading...</h1></body></html>' > /usr/share/nginx/html/index.html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
